CC = gcc
CFLAGS = -Wall -g -I../../practice/headers
TARGET = specific
SRCS = specific.c
OBJS = $(SRCS:.c=.o)
RM = rm

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS)

clean:
	$(RM) $(OBJS) $(TARGET)
